# Generated by Django 3.1.2 on 2020-11-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dummy Project', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
                ('github', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
